site_name: CKS CLI
site_url: https://cks.kubernetes.tn
site_description: A Simple and Comprehensive CLI to prepare for CKS exam 
docs_dir: docs/
repo_name: GitHub
repo_url: https://github.com/kubernetes-tn/cks-cli
edit_uri: ""

nav:
  - HOME: index.md
  - Getting started:
      - Overview: getting-started/overview.md
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quickstart.md
  #     - Troubleshooting: getting-started/troubleshooting.md
  #     - Further Reading: getting-started/further.md
  #     - Credits: getting-started/credit.md
      - Reference:
          - CLI:
              - Overview: getting-started/cli/index.md
              - Cluster: getting-started/cli/cluster.md
  #             - Config: getting-started/cli/config.md
  #             - Filesystem: getting-started/cli/fs.md
  #             - Repository: getting-started/cli/repo.md
  #             - Client: getting-started/cli/client.md
  #             - Server: getting-started/cli/server.md
  # - Vulnerability:
  #     - Scanning:
  #         - Overview: vulnerability/scanning/index.md
  #         - Container Image: vulnerability/scanning/image.md
  #         - Filesystem: vulnerability/scanning/filesystem.md
  #         - Git Repository: vulnerability/scanning/git-repository.md
  #     - Detection:
  #         - OS Packages: vulnerability/detection/os.md
  #         - Language-specific Packages: vulnerability/detection/language.md
  #         - Data Sources: vulnerability/detection/data-source.md
  #         - Supported: vulnerability/detection/supported.md
  #     - Examples:
  #         - Vulnerability Filtering: vulnerability/examples/filter.md
  #         - Report Formats: vulnerability/examples/report.md
  #         - Vulnerability DB: vulnerability/examples/db.md
  #         - Cache: vulnerability/examples/cache.md
  #         - Others: vulnerability/examples/others.md
  # - Misconfiguration:
  #     - Scanning:
  #       - Overview: misconfiguration/index.md
  #       - Infrastructure as Code: misconfiguration/iac.md
  #       - Filesystem: misconfiguration/filesystem.md
  #     - Policy:
  #         - Built-in Policies: misconfiguration/policy/builtin.md
  #         - Exceptions: misconfiguration/policy/exceptions.md
  #     - Custom Policies:
  #         - Overview: misconfiguration/custom/index.md
  #         - Data: misconfiguration/custom/data.md
  #         - Combine: misconfiguration/custom/combine.md
  #         - Testing: misconfiguration/custom/testing.md
  #         - Debugging Policies: misconfiguration/custom/debug.md
  #         - Examples: misconfiguration/custom/examples.md
  #     - Options:
  #         - Policy: misconfiguration/options/policy.md
  #         - Filtering: misconfiguration/options/filter.md
  #         - Report Formats: misconfiguration/options/report.md
  #         - Others: misconfiguration/options/others.md
  #     - Comparison:
  #         - vs Conftest: misconfiguration/comparison/conftest.md
  #         - vs tfsec: misconfiguration/comparison/tfsec.md
  - Advanced:
      - Overview: advanced/index.md
  #     - Plugins: advanced/plugins.md
  #     - Air-Gapped Environment: advanced/air-gap.md
  #     - Integrations:
  #         - Overview: advanced/integrations/index.md
  #         - GitHub Actions: advanced/integrations/github-actions.md
  #         - CircleCI: advanced/integrations/circleci.md
  #         - Travis CI: advanced/integrations/travis-ci.md
  #         - GitLab CI: advanced/integrations/gitlab-ci.md
  #         - AWS CodePipeline: advanced/integrations/aws-codepipeline.md
  #         - AWS Security Hub: advanced/integrations/aws-security-hub.md
  #     - Container Image:
  #         - Embed in Dockerfile: advanced/container/embed-in-dockerfile.md
  #         - Unpacked container image filesystem: advanced/container/unpacked-filesystem.md
  #         - OCI Image: advanced/container/oci.md
  #         - Podman: advanced/container/podman.md
  #         - Private Docker Registries:
  #             - Overview: advanced/private-registries/index.md
  #             - Docker Hub: advanced/private-registries/docker-hub.md
  #             - AWS ECR (Elastic Container Registry): advanced/private-registries/ecr.md
  #             - GCR (Google Container Registry): advanced/private-registries/gcr.md
  #             - Self-Hosted: advanced/private-registries/self.md
  #     - Modes:
  #         - Standalone: advanced/modes/standalone.md
  #         - Client/Server: advanced/modes/client-server.md
      - Maintainer:
          - Help Wanted: advanced/contrib/help-wanted.md
          # - Triage: advanced/contrib/triage.md

theme:
    name: material
    language: 'en'
    logo: img/logo-white.png
    custom_dir: docs/overrides
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - footnotes
  - attr_list
  - pymdownx.tabbed
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  generator: false
  version:
    method: mike
    provider: mike

plugins:
  - search
  - macros
  - minify:
      minify_html: true

# Customization
extra:
  manifest: manifest.webmanifest
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kubernetes-tn
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/abdennour/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/abdennour/
copyright: Copyright &copy; 2021 - 2022 kubernetes.tn
