Parameters:
  PriceClass:
    Type: String
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_ALL
    Default: PriceClass_100
  Environment:
    Type: String
    AllowedValues:
      - prod
      - dev
    Default: prod
  HttpCache:
    Type: Number
    Description: |
      The minimum amount of time (in seconds) that you want objects to stay in 
      CloudFront caches before CloudFront forwards another request 
      to your origin to determine whether the object has been updated. 
    Default: 36000
  
  Hosts:
    Type: CommaDelimitedList
    Description: list of hosts delimited by commaa .ie. app.example.com,app.xpl.co

  SSLCertificateARN:
    Type: String
    Description: ARN of the SSL certificate that was issued in Virginia.
  Version:
    Type: String
    Default: ''
    Description: Useful if you are rebuilding something. Otherwise keep it empty
Conditions:
  IsProduction: !Equals [ !Ref Environment, prod ]
Resources:
#  ----- Buckets  ------
  BucketPolicy:
   Type: AWS::S3::BucketPolicy
   Properties:
     PolicyDocument:
       Version: 2012-10-17
       Statement:
         - Sid: GetS3ObjectsForPublic
           Effect: Allow
           Principal: '*'
           Action:
             - 's3:GetObject'
           Resource:
             - !Join
               - ''
               - - 'arn:aws:s3:::'
                 - !Ref AppBucket
                 - /*
             - !Join
               - ''
               - - 'arn:aws:s3:::'
                 - !Ref AppBucket
     Bucket: !Ref AppBucket
  AppBucket:
    Type: AWS::S3::Bucket
    #DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
      VersioningConfiguration:
        Status: Suspended
      Tags:
        -
          Key: Env
          Value: !Ref Environment
        -
          Key: ServiceName
          Value: APPS

  SPADistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases: !Ref Hosts
        Enabled: true
        DefaultRootObject: index.html
        PriceClass: !Ref PriceClass
        CustomErrorResponses:
          - ErrorCode: '404'
            ResponsePagePath: /404.html
            ResponseCode: '200'
            ErrorCachingMinTTL: '30'
        DefaultCacheBehavior:
          TargetOriginId: !Sub
             - S3-${sourceBucket}
             - sourceBucket: !Ref AppBucket
          ViewerProtocolPolicy: redirect-to-https
          MinTTL: !Ref HttpCache
          AllowedMethods:
            - HEAD
            - GET
            - OPTIONS
          CachedMethods:
            - HEAD
            - GET
            - OPTIONS
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: true
        Origins:
          -
            Id: !Sub
               - S3-${sourceBucket}
               - sourceBucket: !Ref AppBucket
            # {bucket}.s3-website-{region}.amazonaws.com
            # {bucket}.s3.{region}.amazonaws.com
            DomainName: !GetAtt AppBucket.RegionalDomainName
              #  - ${bucketName}.s3.${region}.amazonaws.com
              #  - bucketName: !Ref AppBucket
              #    region: !Ref AWS::Region
            S3OriginConfig: {}
        # Restrictions:
        #   GeoRestriction:
        #     RestrictionType: none
        #     Locations: []
        Restrictions:
          GeoRestriction:
            RestrictionType: blacklist
            Locations:
            - IL
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificateARN
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.1_2016
      Tags:
         -
           Key: Env
           Value: !Ref Environment
         -
           Key: ServiceName
           Value: APPS
  # SPADNS:
  #   Type: AWS::Route53::RecordSetGroup
  #   Properties:
  #     HostedZoneName: example.sa.
  #     RecordSets:
  #     - Name: !Sub
  #        - ${subdomainName}.example.sa.
  #        - { subdomainName: !Ref SubdomainName.value }
  #       Type: A
  #       AliasTarget:
  #         HostedZoneId: Z2FDTNDATAQYW2 # TODO
  #         DNSName: !GetAtt SPADistribution.DomainName

Outputs:
  Bucket:
    Value:
      !Ref AppBucket
  Cloudfront:
    Value: !GetAtt SPADistribution.DomainName
